export const billingTranslations = {
  en: {
    nav_billing: 'Billing', menu_label: 'Menu', preferences: 'Preferences', workspace: 'Workspace', legal_support: 'Legal & support', privacy_policy_full: 'Privacy policy', terms_of_use: 'Terms of use', contact_support: 'Contact support', sign_out: 'Sign out',
    billing_kicker: 'Billing & plans', billing_title: 'Choose the right plan before Stripe goes live.', billing_subtitle: 'Free users get a useful but limited version. Paid plans unlock higher AI limits, CV rebuilding and exports once Stripe is connected.', billing_current_plan: 'Current plan', billing_free_plan: 'Free', billing_month: 'month', billing_popular: 'Best value', billing_coming_soon: 'Stripe checkout coming soon', billing_contact_upgrade: 'Contact / upgrade soon', billing_starter_name: 'Starter', billing_pro_name: 'Pro', billing_free_price: '€0', billing_starter_price: '€5', billing_pro_price: '€10', billing_free_desc: 'For trying Joblytics and improving a few applications.', billing_starter_desc: 'For active job seekers applying every week.', billing_pro_desc: 'For intensive search, coaching and profile optimization.', billing_feature_ats_3: '3 ATS analyses / month', billing_feature_ats_40: '40 ATS analyses / month', billing_feature_ats_200: '200 ATS analyses / month', billing_feature_profile_1: '1 LinkedIn profile AI optimization / month', billing_feature_profile_10: '10 LinkedIn profile AI optimizations / month', billing_feature_profile_60: '60 LinkedIn profile AI optimizations / month', billing_feature_history: 'Application history', billing_feature_cv_builder_locked: 'CV Rebuilder and exports locked', billing_feature_cv_builder: 'CV Rebuilder and exports', billing_feature_priority: 'Higher AI usage limits', billing_feature_future: 'Future premium tools included', billing_note_title: 'Stripe setup note', billing_note_body: 'When you create Stripe prices, connect checkout buttons to Starter and Pro. The backend already expects subscription metadata such as subscription_plan and subscription_status.', billing_free_limit_title: 'Free plan protection', billing_free_limit_body: 'Free usage is counted by account, device and hashed request identity to reduce repeated free use from the same environment.', billing_status_ready: 'Ready for Stripe integration', billing_status_body: 'The billing page is in place. Next step is adding Stripe checkout and webhook endpoints after products/prices are created.',
    upgrade_kicker: 'Upgrade required', upgrade_title: 'You reached your free plan limit', upgrade_body: 'Upgrade to Starter or Pro to keep analyzing jobs, rebuilding CVs and optimizing your profile.', upgrade_cta: 'View plans', upgrade_analyze_title: 'Free analysis limit reached', upgrade_analyze_body: 'You have used your available free ATS analyses. Upgrade to keep checking jobs and improving your CV match.', upgrade_profile_title: 'Profile optimization limit reached', upgrade_profile_body: 'You have used your free LinkedIn profile optimization. Upgrade to continue improving your recruiter positioning.'
  },
  fr: {
    nav_billing: 'Facturation', menu_label: 'Menu', preferences: 'Préférences', workspace: 'Espace de travail', legal_support: 'Légal & support', privacy_policy_full: 'Politique de confidentialité', terms_of_use: 'Conditions d’utilisation', contact_support: 'Contacter le support', sign_out: 'Se déconnecter',
    billing_kicker: 'Facturation & offres', billing_title: 'Choisissez le bon plan avant l’activation de Stripe.', billing_subtitle: 'Les utilisateurs gratuits ont une version utile mais limitée. Les plans payants débloquent plus d’analyses IA, la reconstruction du CV et les exports une fois Stripe connecté.', billing_current_plan: 'Plan actuel', billing_free_plan: 'Gratuit', billing_month: 'mois', billing_popular: 'Meilleur choix', billing_coming_soon: 'Paiement Stripe bientôt disponible', billing_contact_upgrade: 'Contact / upgrade bientôt', billing_starter_name: 'Starter', billing_pro_name: 'Pro', billing_free_price: '0 €', billing_starter_price: '5 €', billing_pro_price: '10 €', billing_free_desc: 'Pour tester Joblytics et améliorer quelques candidatures.', billing_starter_desc: 'Pour les candidats actifs qui postulent chaque semaine.', billing_pro_desc: 'Pour une recherche intensive, coaching et optimisation de profil.', billing_feature_ats_3: '3 analyses ATS / mois', billing_feature_ats_40: '40 analyses ATS / mois', billing_feature_ats_200: '200 analyses ATS / mois', billing_feature_profile_1: '1 optimisation IA du profil LinkedIn / mois', billing_feature_profile_10: '10 optimisations IA du profil LinkedIn / mois', billing_feature_profile_60: '60 optimisations IA du profil LinkedIn / mois', billing_feature_history: 'Historique des candidatures', billing_feature_cv_builder_locked: 'CV Rebuilder et exports verrouillés', billing_feature_cv_builder: 'CV Rebuilder et exports', billing_feature_priority: 'Limites IA plus élevées', billing_feature_future: 'Futurs outils premium inclus', billing_note_title: 'Note de configuration Stripe', billing_note_body: 'Quand vous créez les prix Stripe, connectez les boutons de paiement à Starter et Pro. Le backend attend déjà des métadonnées comme subscription_plan et subscription_status.', billing_free_limit_title: 'Protection du plan gratuit', billing_free_limit_body: 'L’usage gratuit est compté par compte, appareil et identité de requête hachée pour limiter la réutilisation gratuite depuis le même environnement.', billing_status_ready: 'Prêt pour l’intégration Stripe', billing_status_body: 'La page de facturation est en place. La prochaine étape est d’ajouter les endpoints Stripe checkout et webhook après création des produits/prix.',
    upgrade_kicker: 'Upgrade requis', upgrade_title: 'Vous avez atteint la limite gratuite', upgrade_body: 'Passez à Starter ou Pro pour continuer à analyser des offres, adapter vos CV et optimiser votre profil.', upgrade_cta: 'Voir les offres', upgrade_analyze_title: 'Limite d’analyses gratuites atteinte', upgrade_analyze_body: 'Vous avez utilisé vos analyses ATS gratuites. Passez à un plan payant pour continuer à vérifier les offres et améliorer votre CV.', upgrade_profile_title: 'Limite d’optimisation profil atteinte', upgrade_profile_body: 'Vous avez utilisé votre optimisation LinkedIn gratuite. Passez à un plan payant pour continuer à améliorer votre positionnement recruteur.'
  },
  es: {}, de: {}, it: {}, pt: {}
}

;['es','de','it','pt'].forEach(code => { billingTranslations[code] = { ...billingTranslations.en, ...billingTranslations[code] } })