export const postAnalysisTranslations = {
  en: {
    job_offer: 'Job offer', untitled_position: 'Untitled position', location: 'Location', work_mode: 'Work mode', contract: 'Contract', salary: 'Salary', experience: 'Experience', posted: 'Posted', languages: 'Languages', posting_red_flags: 'Posting red flags', view_original: 'View original', copy_link: 'Copy link', work_remote: 'Remote', work_hybrid: 'Hybrid', work_onsite: 'On-site', contract_internship: 'Internship', contract_apprenticeship: 'Apprenticeship', contract_temp: 'Temp', salary_below_market: 'below market', salary_above_market: 'above market', salary_market: 'market',
    your_fitscore: 'Your FitScore', fitscore_strong: 'Strong fit', fitscore_solid: 'Solid fit', fitscore_borderline: 'Borderline', fitscore_weak: 'Weak fit', from_last_run: 'from last run', ats_passthrough: 'ATS pass-through', interview_chance: 'Interview chance',
    next_steps_success_kicker: 'Strong match', next_steps_success_title: 'Great fit! Time to apply.', next_steps_success_desc: 'Your CV is well-aligned with this role. Generate a tailored cover letter to make a strong first impression.', next_steps_success_cta: '✉️ Generate cover letter', next_steps_apply: 'Apply now →', next_steps_medium_kicker: 'Close match', next_steps_medium_title: "You’re close — let’s polish", next_steps_medium_desc: 'A few targeted improvements could push your score over 75. Open CV Coach to see exactly what to fix.', next_steps_medium_cta: '🎤 Open CV Coach', next_steps_run_another: '↻ Try another job', next_steps_low_kicker: 'Needs work', next_steps_low_title: 'Your CV needs significant tuning for this role', next_steps_low_desc: 'Do not apply yet — most candidates improve their score by 20+ points after rewriting with CV Coach. It is worth the 10 minutes.', next_steps_low_cta: '🛠 Fix my CV with Coach',
    salary_conf_high: 'High confidence', salary_conf_medium: 'Medium confidence', salary_conf_low: 'Low confidence', salary_negotiation_kicker: 'Negotiation insight', salary_estimate_kicker: 'Salary estimate', salary_target: 'Target', salary_posted_in_offer: 'Posted in this job', salary_typical_market: 'Typical market range', salary_target_label: 'Realistic target', salary_stretch_label: 'Stretch ask', salary_leverage_kicker: 'Why you can ask higher', salary_strategy_kicker: 'Strategy', salary_disclaimer: 'AI estimate based on training data — verify with Glassdoor, levels.fyi, or PayScale for your exact city.',
    seniority_alignment: 'Seniority alignment', your_level: 'Your level', job_level: 'Job level', year: 'year', years: 'years', level_intern: 'Intern', level_junior: 'Junior', level_mid: 'Mid-level', level_senior: 'Senior', level_lead: 'Lead', level_staff_principal: 'Staff/Principal', level_executive: 'Executive', interview_prep_title: 'Interview prep', interview_prep_subtitle: 'Personalized prep for this role — based on your CV.', likely_questions: 'Likely questions', your_edges_to_lean_on: 'Your edges to lean on', weak_spots: 'Weak spots to prepare', example: 'Example',
    cv_preview_warn: 'Verify your CV was read correctly', cv_preview_title: 'What we read from your CV', cv_preview_warn_desc: 'Less text than expected — your PDF may not be parsing correctly', cv_preview_desc: 'Tap to verify our AI read your CV correctly', extracted_text: 'Extracted text', cv_preview_fix_hint: 'If this looks wrong, your CV may be a scanned image or use unusual formatting. Try saving it as a fresh PDF from Word.',
    cv_rebuilder_kicker: 'CV Rebuilder · Missing keyword adapter', cv_rebuilder_title: 'Generate a job-aligned CV draft.', cv_rebuilder_desc: 'Uses your current CV as the source and adapts it with missing keywords, unmet requirements and quick wins from the ATS analysis.', downloadable: 'Downloadable', cv_source: 'CV source', no_cv_selected: 'No CV selected yet', missing_keywords: 'Missing keywords', keywords_detected: '{count} keywords detected', run_ats_first: 'Run an ATS analysis first', adapted_cv_draft: 'Adapted CV draft', ready_to_download: 'Ready to download', not_generated_yet: 'Not generated yet', job_offer_link: 'Job offer link', job_description: 'Job description', job_description_placeholder: 'Paste the job description here if you want to build without a saved analysis...', cv_upload_first_error: 'Upload or select a CV first. Use the Analyzer upload area so Joblytics can reuse your current CV.', cv_analysis_first_error: 'Run or select an analysis first so Joblytics can use the missing keywords and requirements.', adapting_cv: 'Adapting CV with missing keywords...', generate_adapted_cv: 'Generate adapted CV draft →', cv_preview_added: 'What will be added to the user CV', word_pdf_export: 'Word + PDF export', cv_positioning: 'CV positioning', professional_summary: 'Professional summary', missing_keywords_to_add: 'Missing keywords to add', requirements_to_evidence: 'Requirements to evidence', experience_bullet_updates: 'Experience bullet updates', preparing_word: 'Preparing Word...', download_word_cv: 'Download adapted Word CV', preparing_pdf: 'Preparing PDF...', download_pdf_cv: 'Download adapted PDF CV', cv_rebuilder_note: 'This creates an adapted CV draft from the current CV signals and ATS gaps. Review every line before applying and only keep claims you can prove.', current_cv_signal: 'Current CV signal', job_aligned_update: 'Job-aligned update'
  },
  fr: {
    job_offer: 'Offre d’emploi', untitled_position: 'Poste sans titre', location: 'Localisation', work_mode: 'Mode de travail', contract: 'Contrat', salary: 'Salaire', experience: 'Expérience', posted: 'Publié', languages: 'Langues', posting_red_flags: 'Points d’alerte de l’offre', view_original: 'Voir l’offre originale', copy_link: 'Copier le lien', work_remote: 'Télétravail', work_hybrid: 'Hybride', work_onsite: 'Sur site', contract_internship: 'Stage', contract_apprenticeship: 'Alternance', contract_temp: 'Intérim', salary_below_market: 'sous le marché', salary_above_market: 'au-dessus du marché', salary_market: 'dans le marché',
    your_fitscore: 'Votre FitScore', fitscore_strong: 'Très bon match', fitscore_solid: 'Bon match', fitscore_borderline: 'Limite', fitscore_weak: 'Match faible', from_last_run: 'depuis la dernière analyse', ats_passthrough: 'Passage ATS', interview_chance: 'Chance d’entretien',
    next_steps_success_kicker: 'Match fort', next_steps_success_title: 'Très bon alignement : vous pouvez postuler.', next_steps_success_desc: 'Votre CV est bien aligné avec ce poste. Générez une lettre de motivation adaptée pour renforcer votre candidature.', next_steps_success_cta: '✉️ Générer la lettre', next_steps_apply: 'Postuler maintenant →', next_steps_medium_kicker: 'Match proche', next_steps_medium_title: 'Vous êtes proche — il faut peaufiner', next_steps_medium_desc: 'Quelques améliorations ciblées peuvent faire passer votre score au-dessus de 75. Ouvrez Coach CV pour voir quoi corriger.', next_steps_medium_cta: '🎤 Ouvrir Coach CV', next_steps_run_another: '↻ Tester une autre offre', next_steps_low_kicker: 'À améliorer', next_steps_low_title: 'Votre CV doit être fortement ajusté pour ce poste', next_steps_low_desc: 'Ne postulez pas encore — beaucoup de candidats gagnent plus de 20 points après réécriture avec Coach CV. Cela vaut les 10 minutes.', next_steps_low_cta: '🛠 Corriger mon CV avec le coach',
    salary_conf_high: 'Confiance élevée', salary_conf_medium: 'Confiance moyenne', salary_conf_low: 'Confiance faible', salary_negotiation_kicker: 'Conseil de négociation', salary_estimate_kicker: 'Estimation salariale', salary_target: 'Cible', salary_posted_in_offer: 'Indiqué dans l’offre', salary_typical_market: 'Fourchette de marché habituelle', salary_target_label: 'Cible réaliste', salary_stretch_label: 'Demande haute', salary_leverage_kicker: 'Pourquoi vous pouvez demander plus', salary_strategy_kicker: 'Stratégie', salary_disclaimer: 'Estimation IA basée sur les données d’entraînement — vérifiez avec Glassdoor, levels.fyi ou PayScale pour votre ville exacte.',
    seniority_alignment: 'Alignement séniorité', your_level: 'Votre niveau', job_level: 'Niveau du poste', year: 'an', years: 'ans', level_intern: 'Stagiaire', level_junior: 'Junior', level_mid: 'Intermédiaire', level_senior: 'Senior', level_lead: 'Lead', level_staff_principal: 'Staff/Principal', level_executive: 'Exécutif', interview_prep_title: 'Préparation entretien', interview_prep_subtitle: 'Préparation personnalisée pour ce poste — basée sur votre CV.', likely_questions: 'Questions probables', your_edges_to_lean_on: 'Vos forces à valoriser', weak_spots: 'Points faibles à préparer', example: 'Exemple',
    cv_preview_warn: 'Vérifiez que le CV a été correctement lu', cv_preview_title: 'Ce que nous avons lu dans votre CV', cv_preview_warn_desc: 'Moins de texte que prévu — le PDF est peut-être mal lu', cv_preview_desc: 'Touchez pour vérifier que l’IA a bien lu votre CV', extracted_text: 'Texte extrait', cv_preview_fix_hint: 'Si cela semble incorrect, votre CV est peut-être scanné ou utilise une mise en forme inhabituelle. Essayez de l’enregistrer en nouveau PDF depuis Word.',
    cv_rebuilder_kicker: 'CV Rebuilder · Adaptateur de mots-clés manquants', cv_rebuilder_title: 'Générez un CV adapté à l’offre.', cv_rebuilder_desc: 'Utilise votre CV actuel comme source et l’adapte avec les mots-clés manquants, exigences non couvertes et actions rapides de l’analyse ATS.', downloadable: 'Téléchargeable', cv_source: 'Source CV', no_cv_selected: 'Aucun CV sélectionné', missing_keywords: 'Mots-clés manquants', keywords_detected: '{count} mots-clés détectés', run_ats_first: 'Lancez d’abord une analyse ATS', adapted_cv_draft: 'Brouillon CV adapté', ready_to_download: 'Prêt à télécharger', not_generated_yet: 'Pas encore généré', job_offer_link: 'Lien de l’offre', job_description: 'Description de poste', job_description_placeholder: 'Collez la description de poste ici si vous voulez générer sans analyse sauvegardée...', cv_upload_first_error: 'Téléversez ou sélectionnez d’abord un CV. Utilisez la zone d’upload de l’analyseur pour réutiliser le CV actuel.', cv_analysis_first_error: 'Lancez ou sélectionnez d’abord une analyse pour utiliser les mots-clés et exigences manquantes.', adapting_cv: 'Adaptation du CV avec les mots-clés manquants...', generate_adapted_cv: 'Générer le CV adapté →', cv_preview_added: 'Ce qui sera ajouté au CV utilisateur', word_pdf_export: 'Export Word + PDF', cv_positioning: 'Positionnement CV', professional_summary: 'Résumé professionnel', missing_keywords_to_add: 'Mots-clés manquants à ajouter', requirements_to_evidence: 'Exigences à prouver', experience_bullet_updates: 'Mises à jour des expériences', preparing_word: 'Préparation Word...', download_word_cv: 'Télécharger le CV Word adapté', preparing_pdf: 'Préparation PDF...', download_pdf_cv: 'Télécharger le CV PDF adapté', cv_rebuilder_note: 'Cela crée un brouillon de CV adapté à partir du CV actuel et des écarts ATS. Relisez chaque ligne avant de postuler et gardez uniquement les éléments que vous pouvez prouver.', current_cv_signal: 'Signal du CV actuel', job_aligned_update: 'Mise à jour alignée à l’offre'
  },
  es: {}, de: {}, it: {}, pt: {}
}

;['es','de','it','pt'].forEach(code => { postAnalysisTranslations[code] = { ...postAnalysisTranslations.en, ...postAnalysisTranslations[code] } })