export const premiumTranslations = {
  en: {
    dashboard: 'Dashboard', career_workspace: 'Career growth workspace', primary_navigation: 'Primary navigation', mobile_navigation: 'Mobile navigation', go_to_dashboard: 'Go to dashboard', new_check: 'New check', menu: 'Menu',
    career_growth_dashboard: 'Career growth dashboard', good_morning: 'Good morning', good_afternoon: 'Good afternoon', good_evening: 'Good evening', career_dash_intro: 'Your personal workspace to improve your CV, prepare stronger interviews, track progress, and build a daily job-search rhythm.', run_ats_check: 'Run ATS Check', open_cv_coach: 'Open CV Coach', best_score_label: 'best score', next_recommended_action: 'Next recommended action', complete_todays_challenge: "Complete today’s challenge", daily_improvements_compound: 'Small daily improvements compound into a stronger profile and better applications.', ats_checks: 'ATS checks', total_analyses: 'total analyses', average_score: 'Average score', across_checks: 'across checks', across_all_checks: 'across all checks', best_score: 'Best score', highest_match: 'highest match', highest_role_match: 'highest role match', current_streak: 'Current streak', career_actions: 'career actions', todays_challenge: "Today’s challenge", why_it_matters: 'Why it matters', before: 'Before', after: 'After', hide_example: 'Hide example', show_example: 'Show example', completed_today: 'Completed today ✓', mark_complete: 'Mark as complete', guided_career_paths: 'Guided career paths', choose_next_move: 'Choose your next move', improve_my_cv: 'Improve my CV', improve_my_cv_text: 'Fix ATS blockers, sharpen your summary, and rewrite weak bullets.', prepare_interviews: 'Prepare interviews', prepare_interviews_text: 'Build your pitch, STAR examples, and confident answers.', apply_smarter: 'Apply smarter', apply_smarter_text: 'Match keywords, target better jobs, and track applications.', recent_activity: 'Recent activity', your_latest_analyses: 'Your latest analyses', view_history: 'View history', recent_check: 'Recent check', run_first_check: 'Run first check', weekly_goal: 'Weekly goal', complete_five_actions: 'Complete five meaningful career actions this week.', momentum: 'Momentum', best_streak: 'best streak', coach_insight: 'Coach insight', measurable_achievements_title: 'Make your achievements measurable.', measurable_achievements_text: 'Replace responsibilities with quantified outcomes. Use team size, ticket volume, users supported, SLA impact, or project scope.',
    application_intelligence: 'Application intelligence', history_board: 'History board', history_board_desc: 'A complete view of your job-search performance. Compare ATS scores, review saved analyses, identify strong opportunities, and reopen any role to improve your CV match.', new_ats_check: 'New ATS check', current_archive: 'Current archive', visible_after_filters: 'visible after filters', score_trend: 'Score trend', progress_over_time: 'Progress over time', verdict_breakdown_premium: 'Verdict breakdown', match_quality: 'Match quality', saved_analyses: 'Saved analyses', archive_help: 'Search, filter, and reopen any job analysis from your archive.', visible_results: 'Visible results', current_filtered_view: 'current filtered view', strong_applications: 'strong applications', try_another_filter: 'Try another filter or search term.', no_match_filter_premium: 'No analyses match this filter.', job_analysis: 'Job analysis', unknown: 'Unknown', delete_analysis: 'Delete analysis', analyses_label: 'analyses', avg_score_short: 'avg score',
    ats_analyzer: 'ATS Analyzer', analyze_job_match: 'Analyze a job match', analyze_job_match_desc: 'Paste a job URL or job description, upload your CV, and get your ATS match score with improvement suggestions.', how_it_works: 'How it works', three_steps_application: 'Three steps to a stronger application', add_the_job: 'Add the job', add_the_job_desc: 'Use a URL or paste the full job description.', upload_your_cv: 'Upload your CV', upload_your_cv_desc: 'We compare your CV against the role requirements.', improve_your_match: 'Improve your match', improve_your_match_desc: 'Get score, missing keywords, gaps, and quick wins.', pro_tip: 'Pro tip', paste_mode_reliable: 'Paste mode is more reliable', paste_mode_reliable_desc: 'LinkedIn, Indeed, and some job boards block automated reading. For best results, paste the job description text directly.', processing_time: 'Processing takes ~15 seconds', job_description_text: 'Job description text', paste_full_job_description: 'Paste the full job description here...',
    cv_coach_kicker: 'CV Coach', turn_analysis_action: 'Turn analysis into action', cv_coach_intro: 'Transform ATS results into stronger CV bullets, sharper keywords, clearer achievements, and a tailored cover letter for each opportunity.', current_coaching_focus: 'Current coaching focus', selected_score: 'selected score', select_analysis: 'Select analysis', choose_job_improve: 'Choose the job you want to improve for', cv_intelligence: 'CV intelligence', quick_wins_label: 'Quick wins', missing_keywords_label: 'Missing keywords', your_edges_label: 'Your edges', strengths_to_highlight: 'Strengths to highlight', gaps_label: 'Gaps', cover_letter_label: 'Cover letter', cover_letter_ai_tailored: 'AI-generated and tailored for this role.', generated_tailored_role: 'AI-generated and tailored for this role.', copied: 'Copied', copy: 'Copy', example: 'Example', add_to_cv: 'Add these to your CV', tap_copy_cv: 'Tap to copy, then add to your CV', address_before_applying: 'Address these before applying', no_analyses_yet: 'No analyses yet', coach_empty_premium: 'Run an analysis first to get CV coaching and cover letter generation.', add_full_name_error: 'Please add your full name first.', save_name_error: 'Could not save your name. Please try again.', cover_letter_error: 'Could not generate cover letter. Please try again.', writing_cover_letter: 'Writing your cover letter...'
  },
  fr: {
    dashboard: 'Tableau de bord', career_workspace: 'Espace de progression carrière', primary_navigation: 'Navigation principale', mobile_navigation: 'Navigation mobile', go_to_dashboard: 'Aller au tableau de bord', new_check: 'Nouvelle analyse', menu: 'Menu',
    career_growth_dashboard: 'Tableau de bord carrière', good_morning: 'Bonjour', good_afternoon: 'Bon après-midi', good_evening: 'Bonsoir', career_dash_intro: 'Votre espace personnel pour améliorer votre CV, préparer des entretiens plus solides, suivre vos progrès et construire une routine de recherche d’emploi.', run_ats_check: 'Lancer une analyse ATS', open_cv_coach: 'Ouvrir le CV Coach', best_score_label: 'meilleur score', next_recommended_action: 'Prochaine action recommandée', complete_todays_challenge: 'Terminer le défi du jour', daily_improvements_compound: 'De petites améliorations quotidiennes construisent un meilleur profil et de meilleures candidatures.', ats_checks: 'Analyses ATS', total_analyses: 'analyses au total', average_score: 'Score moyen', across_checks: 'sur toutes les analyses', across_all_checks: 'sur toutes les analyses', best_score: 'Meilleur score', highest_match: 'meilleure correspondance', highest_role_match: 'meilleure correspondance', current_streak: 'Série actuelle', career_actions: 'actions carrière', todays_challenge: 'Défi du jour', why_it_matters: 'Pourquoi c’est important', before: 'Avant', after: 'Après', hide_example: 'Masquer l’exemple', show_example: 'Afficher l’exemple', completed_today: 'Terminé aujourd’hui ✓', mark_complete: 'Marquer comme terminé', guided_career_paths: 'Parcours guidés', choose_next_move: 'Choisissez votre prochaine action', improve_my_cv: 'Améliorer mon CV', improve_my_cv_text: 'Corrigez les blocages ATS, clarifiez votre résumé et réécrivez les points faibles.', prepare_interviews: 'Préparer les entretiens', prepare_interviews_text: 'Construisez votre pitch, vos exemples STAR et des réponses convaincantes.', apply_smarter: 'Postuler plus intelligemment', apply_smarter_text: 'Alignez les mots-clés, ciblez de meilleures offres et suivez vos candidatures.', recent_activity: 'Activité récente', your_latest_analyses: 'Vos dernières analyses', view_history: 'Voir l’historique', recent_check: 'Analyse récente', run_first_check: 'Lancer la première analyse', weekly_goal: 'Objectif hebdomadaire', complete_five_actions: 'Réalisez cinq actions carrière importantes cette semaine.', momentum: 'Momentum', best_streak: 'meilleure série', coach_insight: 'Conseil du coach', measurable_achievements_title: 'Rendez vos réussites mesurables.', measurable_achievements_text: 'Remplacez les responsabilités par des résultats chiffrés : taille d’équipe, volume de tickets, utilisateurs supportés, impact SLA ou périmètre projet.',
    application_intelligence: 'Intelligence de candidature', history_board: 'Historique', history_board_desc: 'Une vue complète de vos performances de recherche d’emploi. Comparez les scores ATS, consultez vos analyses sauvegardées, identifiez les meilleures opportunités et rouvrez un poste pour améliorer votre CV.', new_ats_check: 'Nouvelle analyse ATS', current_archive: 'Archive actuelle', visible_after_filters: 'visibles après filtres', score_trend: 'Évolution du score', progress_over_time: 'Progression dans le temps', verdict_breakdown_premium: 'Répartition des verdicts', match_quality: 'Qualité de correspondance', saved_analyses: 'Analyses sauvegardées', archive_help: 'Recherchez, filtrez et rouvrez toute analyse depuis votre archive.', visible_results: 'Résultats visibles', current_filtered_view: 'vue filtrée actuelle', strong_applications: 'candidatures fortes', try_another_filter: 'Essayez un autre filtre ou terme de recherche.', no_match_filter_premium: 'Aucune analyse ne correspond à ce filtre.', job_analysis: 'Analyse de poste', unknown: 'Inconnu', delete_analysis: 'Supprimer l’analyse', analyses_label: 'analyses', avg_score_short: 'score moyen',
    ats_analyzer: 'Analyseur ATS', analyze_job_match: 'Analyser une correspondance de poste', analyze_job_match_desc: 'Collez une URL ou une description d’offre, téléchargez votre CV et obtenez votre score ATS avec des suggestions d’amélioration.', how_it_works: 'Comment ça marche', three_steps_application: 'Trois étapes pour une meilleure candidature', add_the_job: 'Ajoutez l’offre', add_the_job_desc: 'Utilisez une URL ou collez la description complète.', upload_your_cv: 'Téléchargez votre CV', upload_your_cv_desc: 'Nous comparons votre CV aux exigences du poste.', improve_your_match: 'Améliorez votre correspondance', improve_your_match_desc: 'Obtenez le score, les mots-clés manquants, les écarts et les actions rapides.', pro_tip: 'Astuce', paste_mode_reliable: 'Le mode collage est plus fiable', paste_mode_reliable_desc: 'LinkedIn, Indeed et certains job boards bloquent la lecture automatique. Pour de meilleurs résultats, collez directement le texte de l’offre.', processing_time: 'Le traitement prend environ 15 secondes', job_description_text: 'Texte de l’offre', paste_full_job_description: 'Collez la description complète du poste ici...',
    cv_coach_kicker: 'CV Coach', turn_analysis_action: 'Transformer l’analyse en actions', cv_coach_intro: 'Transformez vos résultats ATS en meilleurs points de CV, mots-clés plus précis, réalisations plus claires et lettre de motivation adaptée à chaque opportunité.', current_coaching_focus: 'Priorité actuelle du coaching', selected_score: 'score sélectionné', select_analysis: 'Sélectionner une analyse', choose_job_improve: 'Choisissez le poste que vous voulez améliorer', cv_intelligence: 'Intelligence CV', quick_wins_label: 'Actions rapides', missing_keywords_label: 'Mots-clés manquants', your_edges_label: 'Vos atouts', strengths_to_highlight: 'Forces à mettre en avant', gaps_label: 'Écarts', cover_letter_label: 'Lettre de motivation', cover_letter_ai_tailored: 'Générée par IA et adaptée à ce poste.', generated_tailored_role: 'Générée par IA et adaptée à ce poste.', copied: 'Copié', copy: 'Copier', example: 'Exemple', add_to_cv: 'À ajouter à votre CV', tap_copy_cv: 'Cliquez pour copier, puis ajoutez à votre CV', address_before_applying: 'À corriger avant de postuler', no_analyses_yet: 'Aucune analyse pour le moment', coach_empty_premium: 'Lancez d’abord une analyse pour obtenir du coaching CV et générer une lettre de motivation.', add_full_name_error: 'Veuillez d’abord ajouter votre nom complet.', save_name_error: 'Impossible d’enregistrer votre nom. Veuillez réessayer.', cover_letter_error: 'Impossible de générer la lettre de motivation. Veuillez réessayer.', writing_cover_letter: 'Rédaction de votre lettre de motivation...'
  },
  es: {}, de: {}, it: {}, pt: {}
}

const challengeTranslations = {
  fr: {
    'cv-bullet-impact': { category: 'CV', title: 'Améliorer un point du CV', description: 'Transformez une responsabilité générique en réussite mesurable.', why: 'Les recruteurs cherchent l’impact, pas seulement les tâches.', task: 'Choisissez un point faible de votre CV et réécrivez-le avec action, périmètre et résultat.', exampleBefore: 'Gestion de l’équipe support IT.', exampleAfter: 'Pilotage d’une équipe support IT de 6 personnes, avec une amélioration de 32 % du temps de résolution sur plus de 400 demandes mensuelles.' },
    'cv-summary-focus': { category: 'CV', title: 'Clarifier votre résumé professionnel', description: 'Rendez votre résumé plus ciblé et plus lisible pour les recruteurs.', why: 'Un bon résumé aide à comprendre votre valeur en quelques secondes.', task: 'Rédigez un résumé en 3 lignes avec votre rôle, vos forces et votre valeur mesurable.', exampleBefore: 'Professionnel IT expérimenté avec de bonnes compétences techniques.', exampleAfter: 'Responsable IT avec plus de 10 ans d’expérience en support, infrastructure et technologies workplace. Compétent en Intune, ITSM, gestion des terminaux et service delivery.' },
    'interview-pitch': { category: 'Entretien', title: 'Préparer votre pitch de 30 secondes', description: 'Créez une réponse claire à « Parlez-moi de vous ».', why: 'Votre première réponse donne le ton de l’entretien.', task: 'Rédigez un pitch court qui couvre qui vous êtes, ce que vous faites bien et le poste que vous visez.', exampleBefore: 'Je travaille dans l’informatique et j’ai fait du support et du management.', exampleAfter: 'Je suis Responsable IT avec une solide expérience en opérations support, gestion des terminaux et service delivery. J’aide les équipes à améliorer l’expérience utilisateur, structurer les processus support et fournir des services IT fiables.' },
    'skills-priority': { category: 'CV', title: 'Prioriser vos compétences clés', description: 'Choisissez les 8 à 12 compétences les plus adaptées à votre poste cible.', why: 'Trop de compétences génériques diluent votre positionnement.', task: 'Retirez les compétences faibles ou dépassées et gardez celles qui correspondent le mieux au poste visé.', exampleBefore: 'Microsoft Office, Windows, Communication, Travail d’équipe, Matériel, Logiciel, IT.', exampleAfter: 'Microsoft Intune, Autopilot, ITSM, Jira, Freshdesk, ITIL, Sécurité endpoint, Microsoft 365, Gestion SLA.' },
    'achievement-metrics': { category: 'CV', title: 'Ajouter des chiffres à vos réussites', description: 'Ajoutez une preuve mesurable à une partie de votre expérience.', why: 'Les chiffres rendent votre contribution plus crédible.', task: 'Ajoutez une métrique : taille d’équipe, volume de tickets, temps de résolution, appareils gérés, utilisateurs supportés, budget ou durée de projet.', exampleBefore: 'Amélioration des processus support.', exampleAfter: 'Standardisation des processus support pour plus de 500 utilisateurs, améliorant la visibilité SLA et réduisant les incidents récurrents.' },
    'application-message': { category: 'Recherche d’emploi', title: 'Écrire un message de candidature plus fort', description: 'Créez un message court à envoyer avec une candidature ou à un recruteur.', why: 'Un message clair peut augmenter le taux de réponse.', task: 'Rédigez un message en 4 lignes : intérêt pour le poste, expérience pertinente, preuve et appel à l’échange.', exampleBefore: 'Bonjour, je suis intéressé par ce poste. Veuillez trouver mon CV.', exampleAfter: 'Bonjour, je suis intéressé par le poste de Responsable IT. J’apporte une forte expérience en leadership support, gestion endpoint et opérations ITSM. Je serais ravi d’échanger sur la façon dont je peux améliorer le service delivery et l’expérience utilisateur.' }
  }
}

export function getPremiumTranslation(lang, key, fallback) {
  return premiumTranslations[lang]?.[key] || premiumTranslations.en?.[key] || fallback || key
}

export function getLocalizedChallenge(challenge, lang) {
  return { ...challenge, ...(challengeTranslations[lang]?.[challenge.id] || {}) }
}
