import React from 'react'
import { useLang } from '../context/LangContext'
import ThemeToggle from '../components/ThemeToggle'
import LangSelector from '../components/LangSelector'

export default function TermsPage({ onBack }) {
  const { t } = useLang()

  return (
    <div style={{ minHeight: '100dvh', background: 'var(--bg)', padding: '24px 20px 60px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 }}>
          <button onClick={onBack || (() => window.history.back())} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontSize: 14, padding: 0 }}>
            ← {t('back') || 'Back'}
          </button>
          <div style={{ display: 'flex', gap: 8 }}>
            <LangSelector />
            <ThemeToggle />
          </div>
        </div>

        <h1 style={{ fontFamily: 'Syne, sans-serif', fontSize: 28, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 8 }}>
          {t('footer_terms') || 'Terms of Service'}
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 36 }}>
          {t('last_updated') || 'Last updated'}: {new Date().toLocaleDateString()}
        </p>

        {[
          { title: '1. Service description', body: 'FitScore is a free web service that helps job seekers analyze their CV against job postings using AI-powered ATS simulation. The service provides ATS scoring, seniority alignment analysis, and interview preparation guidance.' },
          { title: '2. Account', body: 'To use FitScore you need to create an account with a valid email address. You are responsible for maintaining the security of your account and for all activities under it.' },
          { title: '3. Acceptable use', body: 'You agree not to: (a) abuse rate limits or attempt to circumvent them, (b) upload malicious content or files, (c) attempt to reverse-engineer the service, (d) use the service for any illegal purpose, (e) impersonate another person.' },
          { title: '4. Service availability', body: 'FitScore is provided "as is" without warranty. We do our best to maintain uptime but cannot guarantee uninterrupted service. We reserve the right to modify or discontinue features at any time.' },
          { title: '5. AI-generated content disclaimer', body: 'Analyses are generated by AI and are intended as guidance only. They do not guarantee job application success. Final judgment about applying to any job remains with you.' },
          { title: '6. Data and privacy', body: 'Your personal data is handled per our Privacy Policy. We comply with RGPD/GDPR. You can delete your account and all associated data at any time.' },
          { title: '7. Liability limitation', body: 'To the fullest extent permitted by law, FitScore is not liable for any indirect, incidental, or consequential damages arising from use of the service, including missed job opportunities or rejected applications.' },
          { title: '8. Changes to terms', body: 'We may update these terms from time to time. Significant changes will be notified to users via email. Continued use after changes constitutes acceptance.' },
          { title: '9. Governing law', body: 'These terms are governed by French law. Any disputes will be resolved in French courts, subject to applicable EU consumer protection laws.' },
          { title: '10. Contact', body: 'For questions about these terms, contact us at hello@fitscore.app.' }
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: 28 }}>
            <h2 style={{ fontFamily: 'Syne, sans-serif', fontSize: 15, fontWeight: 600, color: 'var(--accent)', marginBottom: 10 }}>{title}</h2>
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.75 }}>{body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
