import { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } from 'docx'
import { saveAs } from 'file-saver'
import { jsPDF } from 'jspdf'

const ACCENT = 'B5663C'
const NAVY = '10182B'
const MUTED = '5F6472'

const clean = value => String(value || '').replace(/\s+/g, ' ').trim()
const fileSafe = value => clean(value).replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').slice(0, 50) || 'cv-builder'

function heading(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 100 },
    border: { bottom: { color: ACCENT, space: 3, style: BorderStyle.SINGLE, size: 6 } },
    children: [new TextRun({ text: text.toUpperCase(), bold: true, color: ACCENT, size: 22, font: 'Calibri' })]
  })
}

function body(text) {
  return new Paragraph({
    spacing: { after: 100 },
    children: [new TextRun({ text: clean(text), color: NAVY, size: 20, font: 'Calibri' })]
  })
}

function bullet(text) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 70 },
    children: [new TextRun({ text: clean(text), color: NAVY, size: 20, font: 'Calibri' })]
  })
}

export function makeCvBuilderExportModel(preview) {
  const p = preview || {}
  return {
    title: clean(p.header?.after || 'Target CV Rewrite'),
    source: clean(p.header?.before || 'Current CV'),
    summary: clean(p.summary?.after || 'Job-aligned professional summary preview.'),
    keywords: clean(p.keywords?.after || 'Role-specific keywords will be added naturally.'),
    achievements: clean(p.achievements?.after || 'Achievements will be reframed with measurable impact.'),
    disclaimer: 'Draft generated by Joblytics CV Builder foundation. Review carefully before sending. Do not add experience you cannot evidence.',
    changes: [
      ['Header positioning', p.header?.before, p.header?.after],
      ['Professional summary', p.summary?.before, p.summary?.after],
      ['Keyword alignment', p.keywords?.before, p.keywords?.after],
      ['Achievement framing', p.achievements?.before, p.achievements?.after]
    ].filter(row => row[1] || row[2])
  }
}

export async function downloadCvBuilderDocx(preview, opts = {}) {
  const model = makeCvBuilderExportModel(preview)
  const fileName = opts.fileName || `Joblytics-CV-Builder-${fileSafe(model.title)}.docx`

  const children = [
    new Paragraph({
      spacing: { after: 60 },
      children: [new TextRun({ text: model.title, bold: true, color: NAVY, size: 36, font: 'Calibri' })]
    }),
    new Paragraph({
      spacing: { after: 220 },
      children: [new TextRun({ text: `Based on: ${model.source}`, color: MUTED, size: 18, font: 'Calibri' })]
    }),
    heading('Rewritten profile'),
    body(model.summary),
    heading('Keyword strategy'),
    body(model.keywords),
    heading('Achievement framing'),
    bullet(model.achievements),
    heading('Change log')
  ]

  model.changes.forEach(([title, before, after]) => {
    children.push(new Paragraph({ spacing: { before: 120, after: 50 }, children: [new TextRun({ text: title, bold: true, color: NAVY, size: 22, font: 'Calibri' })] }))
    if (before) children.push(body(`Before: ${before}`))
    if (after) children.push(body(`After: ${after}`))
  })

  children.push(new Paragraph({ spacing: { before: 260 }, children: [new TextRun({ text: model.disclaimer, color: MUTED, size: 16, italics: true, font: 'Calibri' })] }))

  const doc = new Document({
    creator: 'Joblytics',
    title: 'CV Builder Rewrite Preview',
    styles: { default: { document: { run: { font: 'Calibri', size: 20 } } } },
    sections: [{ properties: { page: { margin: { top: 720, right: 900, bottom: 720, left: 900 } } }, children }]
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, fileName)
}

export function downloadCvBuilderPdf(preview, opts = {}) {
  const model = makeCvBuilderExportModel(preview)
  const fileName = opts.fileName || `Joblytics-CV-Builder-${fileSafe(model.title)}.pdf`
  const pdf = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 48
  const width = pdf.internal.pageSize.getWidth() - margin * 2
  let y = 54

  const addText = (text, size = 10, color = [16, 24, 43], gap = 14, bold = false) => {
    pdf.setFont('helvetica', bold ? 'bold' : 'normal')
    pdf.setFontSize(size)
    pdf.setTextColor(...color)
    const lines = pdf.splitTextToSize(clean(text), width)
    lines.forEach(line => {
      if (y > 770) { pdf.addPage(); y = 54 }
      pdf.text(line, margin, y)
      y += gap
    })
  }

  const addSection = title => {
    y += 12
    addText(title.toUpperCase(), 10, [181, 102, 60], 14, true)
    pdf.setDrawColor(181, 102, 60)
    pdf.line(margin, y - 6, margin + width, y - 6)
    y += 8
  }

  addText(model.title, 22, [16, 24, 43], 25, true)
  addText(`Based on: ${model.source}`, 10, [95, 100, 114], 14)
  addSection('Rewritten profile')
  addText(model.summary, 10, [16, 24, 43], 14)
  addSection('Keyword strategy')
  addText(model.keywords, 10, [16, 24, 43], 14)
  addSection('Achievement framing')
  addText(model.achievements, 10, [16, 24, 43], 14)
  addSection('Change log')
  model.changes.forEach(([title, before, after]) => {
    addText(title, 11, [16, 24, 43], 15, true)
    if (before) addText(`Before: ${before}`, 9, [95, 100, 114], 13)
    if (after) addText(`After: ${after}`, 9, [16, 24, 43], 13)
    y += 6
  })
  addText(model.disclaimer, 8, [95, 100, 114], 11)
  pdf.save(fileName)
}
